development:
  adapter: postgresql
  #encoding: utf8
  database: boiler_development
  pool: 5
  timeout: 5000
  host: localhost
  username: boiler
  password: admin

test:
  adapter: postgresql
  #encoding: utf8
  database: boiler_test
  pool: 5
  timeout: 5000
  host: localhost
  username: boiler
  password: admin

production:
  adapter: postgresql
  #encoding: utf8
  database: boiler_production
  pool: 5
  timeout: 5000
  host: localhost
  username: boiler
  password: admin
