# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfc55b21c15132582d3987f1535fd0a4f03b6a83d61945c4f204df43caca6af3f41235e9e576ac9edf88016b9e01dd581233676c33bd842a1593f847b5ab56ef

test:
  secret_key_base: 8c8a147b7b2fef8d94cc6947a705aa3f43965c0a619b0eb534d7cce1abba2e99b386b553e43a49d3569c3b1a6ae3a4097f1414422afa1f129321492a8a0aa83c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
